### PR TITLE
A talk on ReactNative 

### PR DESCRIPTION
**Pull request by ahmedrizwan**

### CODE REVIEW

**Comment by thirdknife** [comment]
@ahmedrizwan if I'd ask you to break down your talk in 4 components, 5 mins each. How would you do that?

**Comment by thirdknife** [comment]
@ahmedrizwan

**Comment by ahmedrizwan** [comment]
@thirdknife sorry I didn't get any notifications of your comments... Otherwise would've responded earlier... 
I'd say these would be the four components (5 mins each)
1.  Intro to ReactNative and its comparison to Native mobile platforms
2.  Setting things up and a tour of Components
3.  Live demo: A basic Todo App using Mobx 
4.  Awesome third party resources/libraries

**Comment by thirdknife** [comment]
@ahmedrizwan I am finalizing your talk. You will be speaking for the meetup on 22nd October.

**Pull request merged**
